### ISSUE TITLE
frontend, react: Progress Bar gets funky at smaller screen sizes[#4]

### ISSUE THREAD

**Issue by vwong031** [ArtrSpace/Artr#4]
![Screenshot 2024-07-02 161813](https://github.com/ArtrSpace/Artr/assets/74090811/3c8eb0c4-bb4d-4a47-93d5-77d2c904faf9)
![Screenshot 2024-07-02 161823](https://github.com/ArtrSpace/Artr/assets/74090811/c6c50b78-0edc-4fad-9d3b-ef5d8e44e20d)
![Screenshot 2024-07-02 161831](https://github.com/ArtrSpace/Artr/assets/74090811/5207dce9-1481-4d8e-a087-edf07b0cebfb)
![Screenshot 2024-07-02 161841](https://github.com/ArtrSpace/Artr/assets/74090811/61a0409b-5928-4bd7-81fd-d39768032268)

**Comment by py1u** [comment]
I've tested the responsiveness for all pages.
suggestions:
- Account Type(1) make a breakline where one box is stacks on top of the other when reaching mobile device range
- Other steps should be simple to adjust to a mobile friendly form
- have one progress node at a time per page:
-heres a initial idea(NOT finalized) to get some inspiration
![image](https://github.com/ArtrSpace/Artr/assets/147663233/def4bdf2-eac9-444f-9f61-966448ffbc76)
 - keep the thread open until we close the issue.

**Comment by py1u** [comment]
I've reviewed your most recent changes.
suggestions-2:

- add spacing to the left margins for text box inputs
![image](https://github.com/ArtrSpace/Artr/assets/147663233/842b906e-df36-40dc-99e1-9b27a2c0f24a)
![image](https://github.com/ArtrSpace/Artr/assets/147663233/ba910727-5464-45c9-81b8-1c6b0b864c67)
![image](https://github.com/ArtrSpace/Artr/assets/147663233/95bacddb-6109-4b64-b2af-942878316c3d)


-add a div container to the signIn.js and create a form box around it.
-background color:` #D9D2FF`
- rounding: try `rounded-md` or `rounded-lg`
- 
- glass morphism design to form:
try this sample code:
`className="h-full w-full bg-purple-200 rounded-md bg-clip-padding backdrop-filter backdrop-blur-lg bg-opacity-10 border border-gray-100"`
